### ISSUE TITLE
BiPlanar_2Partitions.m

### ISSUE THREAD

**Issue by hbbdyzf** [Sebastian-MR/ThinWire_MRIGradientCoilDesign#1]
Hello, I run this code, and find that it has some issue. These wires is very compact. If the section of gradient coil is circle, the results will be better.

**Comment by Sebastian-MR** [comment]
Sorry, i don't understand the question or issue. The BiPlanar example shows that two flat (planar) coils may be optimized with this code, as well.
Cylindrical_SingleLayer.m gives an example of a cylindrical coil. Maybe that is what you are looking for?

**Comment by hbbdyzf** [comment]
Hello, dear Sebastian! The general bi-planar gradient coils are two circle rather two square sections
![gradientcoils](https://user-images.githubusercontent.com/15995318/89101844-6c637000-d436-11ea-859f-a89409eb2548.png)
