### ISSUE TITLE
biplanar gradient coils two circle area

### ISSUE THREAD

**Issue by hbbdyzf** [Sebastian-MR/ThinWire_MRIGradientCoilDesign#2]
Hello, dear Sebastian! The general bi-planar gradient coils are two circle area rather two square sections.
![gradientcoils](https://user-images.githubusercontent.com/15995318/89112571-45895600-d497-11ea-98cf-abf81a046e97.png)

**Comment by Sebastian-MR** [comment]
The coil you showed has another orientation, compared to the one optimized in the code. The current carrying surfaces referred to are oriented in the xy plane. Therefore both current directions have to be considered, since both of them generate a Bz component. The code shown here uses the xz plane- therefore only currents flowing orthogonal to z (in this case x-direction) generate a Bz component. Please write an eMail for further questions.

**Comment by hbbdyzf** [comment]
Hello！Thanks your answer, The wire space is too small if the gradient coils are designed as your way. It is diffcult to process. can you design a Bx gradient coil? 














At 2020-08-03 16:00:00, "Sebastian-MR" <notifications@github.com> wrote:

The coil you showed has another orientation, compared to the one optimized in the code. The current carrying surfaces referred to are oriented in the xy plane. Therefore both current directions have to be considered, since both of them generate a Bz component. The code shown here uses the xz plane- therefore only currents flowing orthogonal to z (in this case x-direction) generate a Bz component. Please write an eMail for further questions.

**Comment by Sebastian-MR** [comment]
The code can be changed and adapted to take all components into account. I am happy to review your additions and contributions to the code!

**Comment by hbbdyzf** [comment]
I use stream function, and calculate the x coil results.  Is this results right?















At 2020-08-04 17:35:17, "Sebastian-MR" <notifications@github.com> wrote:

The code can be changed and adapted to take all components into account. I am happy to review your additions and contributions to the code!

**Comment by Sebastian-MR** [comment]
Please write me an eMail. You'll find my address in the code.

**Comment by hbbdyzf** [comment]
Hello, your de email is sebastian.littin@uniklinik-freiburg.de. it is right?














At 2020-08-06 15:38:31, "Sebastian-MR" <notifications@github.com> wrote:

Please write me an eMail. You'll find my address in the code.
